### ISSUE TITLE
to switch to python 3+

### ISSUE THREAD

**Issue by eugenpar** [saarahy/NGP-LS#2]
It's a pity that 15 months ago, when you were developing this version, you didn't think to switch to python 3+

**Comment by saarahy** [comment]
Hi! 
I started this project 4 years ago, so DEAP wasn't ready for Python version 3. + yet.
You are right a year ago I was able to make the change to a more current version, however it was not my priority.
Soon you will have it updated and even in containers.
Regards!

**Comment by eugenpar** [comment]
Hi!I will look forward to the adapted version, because the development seems promising.I couldn't adapt the existing version for Python3 on my own.
